# Generated by Django 4.2.11 on 2026-02-07 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='lms_core_enrollment_unique_user_course',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
