# Generated by Django 6.0.3 on 2026-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_category_alter_lesson_options_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover image', null=True, upload_to='course_thumbnails/'),
        ),
    ]
