# Generated by Django 6.0.3 on 2026-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Optional cover image URL', null=True),
        ),
    ]
