# Generated by Django 6.0.3 on 2026-05-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_course_thumbnail_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price (0.00 for free)', max_digits=8),
        ),
    ]
